-- GrammarFlow curriculum seed.
-- Run after supabase/schema.sql. Re-runnable and safe for existing projects.

with level_data(title, slug, description, level_order) as (
  values
    ('Absolute Beginner', 'absolute-beginner', 'Start from zero: pronouns, be, basic sentences, questions, negatives, nouns, adjectives, and simple conversation grammar.', 1),
    ('Beginner', 'beginner', 'Build everyday grammar: core tenses, articles, countable nouns, there is/are, can, have, questions, and connectors.', 2),
    ('Elementary', 'elementary', 'Add more control with perfect forms, comparisons, adverbs, modals, prepositions, gerunds, infinitives, and simple paragraphs.', 3),
    ('Pre-Intermediate', 'pre-intermediate', 'Connect ideas with perfect/continuous forms, conditionals, passive voice, reported speech, quantifiers, and practical conversation grammar.', 4),
    ('Intermediate', 'intermediate', 'Compare all major tense systems and build stronger clauses, modals, passive forms, reported speech, linking words, and sentence control.', 5),
    ('Upper-Intermediate', 'upper-intermediate', 'Use advanced conditionals, emphasis, participle clauses, reduced clauses, advanced passives, reporting, and formal writing grammar.', 6),
    ('Advanced', 'advanced', 'Master advanced clause patterns, nominalization, discourse markers, register, tone, punctuation, and professional grammar.', 7),
    ('Expert Grammar / Writing Mastery', 'expert-grammar-writing-mastery', 'Control nuance, style, rhythm, clarity, persuasion, academic writing, technical writing, and native-like grammar patterns.', 8)
)
insert into public.grammar_levels (title, slug, description, level_order, is_published)
select title, slug, description, level_order, true
from level_data
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  level_order = excluded.level_order,
  is_published = true;

with topic_arrays(level_slug, titles) as (
  values
    ('absolute-beginner', array[
      'Verb "to be" - am / is / are',
      'Subject pronouns - I, you, he, she, it, we, they',
      'Object pronouns - me, you, him, her, it, us, them',
      'Possessive adjectives - my, your, his, her, its, our, their',
      'Possessive pronouns - mine, yours, his, hers, ours, theirs',
      'This / That / These / Those',
      'Singular and plural nouns',
      'Basic sentence structure',
      'Basic questions',
      'Basic negatives',
      'Basic adjectives',
      'Basic prepositions of place',
      'Basic prepositions of time',
      'Numbers, dates, and time grammar',
      'Basic conversation grammar'
    ]),
    ('beginner', array[
      'Present simple tense',
      'Present continuous tense',
      'Past simple tense',
      'Future with "will"',
      'Future with "going to"',
      'Articles - a / an / the',
      'Countable and uncountable nouns',
      'Some / any',
      'Much / many / a lot of',
      'There is / there are',
      'Can / cannot',
      'Have / has',
      'Imperatives',
      'Frequency adverbs',
      'Basic conjunctions - and / but / because / so',
      'Basic question words - what, where, when, why, who, how',
      'Basic conversation practice'
    ]),
    ('elementary', array[
      'Past continuous',
      'Present perfect simple',
      'Present perfect vs past simple',
      'Comparative adjectives',
      'Superlative adjectives',
      'Adverbs of manner',
      'Prepositions of movement',
      'Prepositions in / on / at',
      'Modal verbs - can, could, should, must',
      'Requests and offers',
      'Gerunds basic',
      'Infinitives basic',
      'Object and subject questions',
      'Basic phrasal verbs',
      'Basic sentence connectors',
      'Simple paragraph grammar',
      'Conversation practice'
    ]),
    ('pre-intermediate', array[
      'Past perfect',
      'Future continuous',
      'Future perfect basic',
      'Present perfect continuous',
      'Used to',
      'Be used to / get used to',
      'First conditional',
      'Zero conditional',
      'Second conditional',
      'Passive voice basic',
      'Relative clauses basic',
      'Reported speech basic',
      'Modal verbs for advice',
      'Modal verbs for possibility',
      'Too / enough',
      'So / such',
      'Either / neither',
      'Both / all / none',
      'Quantifiers',
      'Conversation practice'
    ]),
    ('intermediate', array[
      'All present tenses comparison',
      'All past tenses comparison',
      'All future forms comparison',
      'Present perfect continuous vs present perfect simple',
      'Past perfect continuous',
      'Third conditional',
      'Mixed conditionals introduction',
      'Passive voice with different tenses',
      'Reported speech with tense changes',
      'Relative clauses defining and non-defining',
      'Gerunds and infinitives advanced',
      'Modals of deduction',
      'Modals of obligation',
      'Modals of permission',
      'Phrasal verbs grammar',
      'Linking words',
      'Sentence clauses',
      'Noun clauses',
      'Adjective clauses',
      'Adverb clauses',
      'Conversation practice'
    ]),
    ('upper-intermediate', array[
      'Advanced tense review',
      'Advanced conditionals',
      'Mixed conditionals',
      'Wish / if only',
      'Inversion basic',
      'Cleft sentences',
      'Emphasis structures',
      'Participle clauses',
      'Reduced relative clauses',
      'Advanced passive voice',
      'Advanced reported speech',
      'Advanced modals',
      'Modal perfect forms',
      'Future in the past',
      'Subjunctive mood',
      'Advanced connectors',
      'Formal and informal grammar',
      'Grammar for emails',
      'Grammar for essays',
      'Conversation practice'
    ]),
    ('advanced', array[
      'Inversion advanced',
      'Fronting',
      'Ellipsis',
      'Substitution',
      'Nominalization',
      'Complex noun phrases',
      'Complex verb patterns',
      'Advanced clause structures',
      'Discourse markers',
      'Hedging language',
      'Academic grammar',
      'Business grammar',
      'Legal/formal grammar basics',
      'Advanced punctuation grammar',
      'Register and tone',
      'Grammar for professional writing',
      'Grammar for presentations',
      'Grammar for arguments',
      'Grammar for storytelling',
      'Conversation practice'
    ]),
    ('expert-grammar-writing-mastery', array[
      'Grammar nuance and meaning',
      'Grammar for clear writing',
      'Grammar for persuasive writing',
      'Grammar for academic essays',
      'Grammar for business communication',
      'Grammar for technical writing',
      'Grammar for storytelling',
      'Grammar for natural conversation',
      'Grammar for fluency',
      'Error correction mastery',
      'Sentence rhythm and variation',
      'Advanced punctuation',
      'Advanced style control',
      'Formality control',
      'Native-like grammar patterns',
      'Grammar review master test',
      'Final full grammar exam'
    ])
),
topic_data as (
  select
    level_slug,
    title,
    case
      when title = 'Present simple tense' then 'present-simple'
      when title = 'Present continuous tense' then 'present-continuous'
      when title = 'Past simple tense' then 'past-simple'
      when title = 'Articles - a / an / the' then 'articles'
      else trim(both '-' from regexp_replace(lower(title), '[^a-z0-9]+', '-', 'g'))
    end as slug,
    'Curriculum topic for ' || title || '. Includes lesson study, practice, review, and tests.' as description,
    ordinality::integer as topic_order
  from topic_arrays
  cross join lateral unnest(titles) with ordinality as topic(title, ordinality)
)
insert into public.grammar_topics (level_id, title, slug, description, topic_order, is_published)
select levels.id, topic_data.title, topic_data.slug, topic_data.description, topic_data.topic_order, true
from topic_data
join public.grammar_levels levels on levels.slug = topic_data.level_slug
on conflict (level_id, slug) do update set
  title = excluded.title,
  description = excluded.description,
  topic_order = excluded.topic_order,
  is_published = true;

with lesson_seed(
  level_slug,
  topic_slug,
  lesson_title,
  lesson_slug,
  difficulty,
  estimated_minutes,
  summary,
  explanation,
  formula,
  usage_when,
  usage_when_not,
  examples,
  common_mistakes,
  wrong_correct_examples,
  short_notes,
  mini_practice,
  correct_sentence,
  wrong_sentence,
  wrong_sentence_two,
  wrong_sentence_three,
  blank_prompt,
  blank_answer,
  tf_prompt,
  tf_answer,
  correction_prompt,
  correction_answer
) as (
  values
    (
      'absolute-beginner',
      'verb-to-be-am-is-are',
      'Verb "to be" - am / is / are',
      'verb-to-be-am-is-are-core',
      'easy',
      18,
      'Learn the forms am, is, and are in positive sentences, negatives, questions, and short answers.',
      'The verb "to be" is one of the first verbs English learners need. It connects a subject to a name, place, feeling, job, description, age, or situation. Use am with I, is with he/she/it and singular nouns, and are with you/we/they and plural nouns.',
      'I am; he/she/it is; you/we/they are. Negative: subject + am/is/are + not. Question: am/is/are + subject?',
      'Use "to be" for identity, feelings, location, age, nationality, jobs, and descriptions.',
      'Do not use do/does with "be" in simple present questions. Say "Is she ready?", not "Does she is ready?"',
      '["I am a student.","You are ready.","He is tired.","She is happy.","It is cold.","We are friends.","They are at school.","My brother is a doctor.","The books are on the table.","Are you okay?"]'::jsonb,
      '["Use am with I, not is.","Use is with he, she, it, and singular nouns.","In questions, put am/is/are before the subject."]'::jsonb,
      '["Wrong: I is happy. | Correct: I am happy.","Wrong: She are my friend. | Correct: She is my friend.","Wrong: Are he ready? | Correct: Is he ready?"]'::jsonb,
      '["Contractions are common: I am = I''m, he is = he''s, they are = they''re.","Short answers repeat the be verb: Yes, I am. No, he isn''t.","Use not after be for negatives."]'::jsonb,
      '["Complete: I ___ a teacher.","Change to a question: She is ready.","Correct the mistake: They is at home."]'::jsonb,
      'She is happy.',
      'She are happy.',
      'I is a student.',
      'Are he ready?',
      'He ___ my brother.',
      'is',
      'The sentence "They are at school" is correct.',
      'True',
      'Correct the sentence: I is tired.',
      'I am tired'
    ),
    (
      'absolute-beginner',
      'subject-pronouns-i-you-he-she-it-we-they',
      'Subject Pronouns',
      'subject-pronouns-core',
      'easy',
      16,
      'Use I, you, he, she, it, we, and they as the subject of a sentence.',
      'A subject pronoun replaces the person or thing doing the action. It helps you avoid repeating names. Subject pronouns come before the verb: I study, she works, they play.',
      'Subject pronoun + verb',
      'Use subject pronouns when the pronoun is the person or thing doing the action.',
      'Do not use object pronouns as subjects. Say "She is here", not "Her is here".',
      '["I live in Baghdad.","You speak English.","He works here.","She likes tea.","It is late.","We study together.","They play football.","My sister is kind. She helps me.","Ali and Omar are friends. They are students.","The phone is new. It is expensive."]'::jsonb,
      '["Do not use me as a subject.","Use it for one thing or animal when the gender is unknown.","Use they for plural people or things."]'::jsonb,
      '["Wrong: Me am ready. | Correct: I am ready.","Wrong: Her is my sister. | Correct: She is my sister.","Wrong: Ali and Omar is here. | Correct: They are here."]'::jsonb,
      '["I is always capitalized.","You can mean one person or many people.","They can refer to people, animals, or things."]'::jsonb,
      '["Replace: Sarah is happy. ___ is happy.","Choose: ___ are my friends. (They / It)","Correct: Me like English."]'::jsonb,
      'She is my sister.',
      'Her is my sister.',
      'Me am ready.',
      'Them are students.',
      'Ali and Dana are here. ___ are ready.',
      'They',
      'The pronoun "I" is always written with a capital letter.',
      'True',
      'Correct the sentence: Me am ready.',
      'I am ready'
    ),
    (
      'beginner',
      'present-simple',
      'Present Simple Tense',
      'present-simple-core',
      'easy',
      22,
      'Use the present simple for habits, routines, facts, schedules, and repeated actions.',
      'The present simple describes things that are generally true or happen again and again. With he, she, it, and singular nouns, add -s or -es to the verb. Questions and negatives use do or does plus the base verb.',
      'Positive: subject + base verb / verb-s. Negative: subject + do/does not + base verb. Question: do/does + subject + base verb?',
      'Use it for routines, facts, permanent situations, schedules, and repeated actions.',
      'Do not use it for actions happening right now. Use present continuous for that.',
      '["I study English every day.","She works from home.","He watches TV at night.","We live near the river.","They play football on Fridays.","Water boils at 100 degrees Celsius.","The shop opens at nine.","My brother likes coffee.","Do you speak English?","She does not eat meat."]'::jsonb,
      '["Do not add -s after does.","Remember -s with he, she, it in positive sentences.","Use the base verb in questions and negatives."]'::jsonb,
      '["Wrong: She work every day. | Correct: She works every day.","Wrong: Does he plays football? | Correct: Does he play football?","Wrong: I am go to school. | Correct: I go to school."]'::jsonb,
      '["Frequency adverbs often go before the main verb: I usually study.","Be is different: She is often late.","Does is for he, she, it, and singular nouns."]'::jsonb,
      '["Complete: She ___ coffee every morning.","Make negative: He likes tea.","Correct: Does she works here?"]'::jsonb,
      'She works every day.',
      'She work every day.',
      'Does he plays football?',
      'I am go to school.',
      'He ___ coffee every morning.',
      'drinks',
      'After does, the main verb stays in the base form.',
      'True',
      'Correct the sentence: She do not play football.',
      'She does not play football'
    ),
    (
      'beginner',
      'past-simple',
      'Past Simple Tense',
      'past-simple-core',
      'easy',
      22,
      'Use the past simple for finished actions and finished time periods.',
      'The past simple talks about actions that started and finished in the past. Regular verbs usually add -ed. Irregular verbs have special past forms. Questions and negatives use did plus the base verb.',
      'Positive: subject + past verb. Negative: subject + did not + base verb. Question: did + subject + base verb?',
      'Use it with finished time words like yesterday, last week, in 2020, ago, and when I was young.',
      'Do not use the past form after did. Say "Did you go?", not "Did you went?"',
      '["I visited my cousin yesterday.","She watched a film last night.","They played football on Monday.","He went to school early.","We ate dinner at eight.","Did you see the message?","I did not understand the question.","My father worked in Basra.","The meeting started late.","She bought a new bag."]'::jsonb,
      '["Use did for questions and negatives.","Use the base verb after did.","Learn common irregular past forms."]'::jsonb,
      '["Wrong: Did you went home? | Correct: Did you go home?","Wrong: She buyed a phone. | Correct: She bought a phone.","Wrong: I didn''t watched TV. | Correct: I didn''t watch TV."]'::jsonb,
      '["Regular verbs often end in -ed.","Some verbs change completely: go -> went, buy -> bought.","Past simple often needs a clear past time."]'::jsonb,
      '["Complete: I ___ my friend yesterday.","Make a question: She visited Paris.","Correct: He didn''t went home."]'::jsonb,
      'She visited Paris last year.',
      'She visit Paris last year.',
      'Did you went home?',
      'I didn''t watched TV.',
      'I ___ my friend yesterday.',
      'visited',
      'After did, use the base verb.',
      'True',
      'Correct the sentence: He didn''t went home.',
      'He did not go home'
    ),
    (
      'beginner',
      'future-with-will',
      'Future Tense: will and going to',
      'future-will-going-to-core',
      'medium',
      24,
      'Use will for decisions, promises, offers, and predictions. Use going to for plans and evidence-based predictions.',
      'English has more than one future form. Will is common for quick decisions, promises, offers, and general predictions. Going to is common for plans decided before now and predictions based on present evidence.',
      'will + base verb; am/is/are + going to + base verb',
      'Use will for instant decisions and promises. Use going to for plans and visible evidence.',
      'Do not use will after going to. Say "I am going to study", not "I am going to will study".',
      '["I will call you later.","She will help us.","It will rain tomorrow.","I am going to study tonight.","They are going to travel next month.","Look at the clouds. It is going to rain.","Will you join us?","He is not going to sell his car.","We will not forget this.","Are you going to cook dinner?"]'::jsonb,
      '["Do not combine will and going to.","Use base verb after will.","Use be before going to."]'::jsonb,
      '["Wrong: I will to call you. | Correct: I will call you.","Wrong: She going to study. | Correct: She is going to study.","Wrong: I am going to will travel. | Correct: I am going to travel."]'::jsonb,
      '["Will is often shortened to ''ll.","Going to is common in spoken English.","Context decides which future form sounds more natural."]'::jsonb,
      '["Complete: I ___ call you later.","Choose: Look at the sky. It ___ rain.","Correct: She going to visit us."]'::jsonb,
      'I will call you later.',
      'I will to call you later.',
      'She going to study tonight.',
      'I am going to will travel.',
      'She ___ going to visit us.',
      'is',
      'Going to needs a form of be before it.',
      'True',
      'Correct the sentence: I will to help you.',
      'I will help you'
    ),
    (
      'absolute-beginner',
      'basic-questions',
      'Basic Questions',
      'basic-questions-core',
      'easy',
      20,
      'Learn how to make simple yes/no questions and basic information questions.',
      'A question asks for information. With be, put am/is/are before the subject. With most other verbs in present simple, use do or does. Question words like what, where, when, why, who, and how come at the beginning.',
      'Be question: am/is/are + subject? Present simple: do/does + subject + base verb? Wh-question: question word + auxiliary + subject + verb?',
      'Use questions to ask about identity, location, time, reason, people, manner, routines, and facts.',
      'Do not keep normal sentence order when a question needs an auxiliary.',
      '["Are you ready?","Is she your sister?","Do you like tea?","Does he work here?","What is your name?","Where do you live?","When does the class start?","Why are you late?","Who is your teacher?","How do you spell this word?"]'::jsonb,
      '["Use does with he, she, it.","Use base verb after do/does.","With be, do not add do/does."]'::jsonb,
      '["Wrong: You are ready? | Correct: Are you ready?","Wrong: Does she works here? | Correct: Does she work here?","Wrong: Do he like coffee? | Correct: Does he like coffee?"]'::jsonb,
      '["Intonation rises in many yes/no questions.","Wh-questions usually ask for specific information.","Short answers are common in conversation."]'::jsonb,
      '["Make a question: She is ready.","Complete: ___ do you live?","Correct: Does he works here?"]'::jsonb,
      'Are you ready?',
      'You are ready?',
      'Does she works here?',
      'Do he like coffee?',
      '___ do you live?',
      'Where',
      'With be, the question starts with am, is, or are.',
      'True',
      'Correct the sentence: Does he works here?',
      'Does he work here'
    ),
    (
      'absolute-beginner',
      'basic-negatives',
      'Basic Negatives',
      'basic-negatives-core',
      'easy',
      18,
      'Learn how to say that something is not true using not, do not, and does not.',
      'A negative sentence says no or shows that something is not true. With be, put not after am/is/are. With most present simple verbs, use do not or does not plus the base verb.',
      'Be: subject + am/is/are + not. Present simple: subject + do/does + not + base verb.',
      'Use negatives to deny facts, habits, states, identity, location, and actions.',
      'Do not use two negative forms together in a simple sentence.',
      '["I am not tired.","She is not at home.","They are not ready.","I do not like onions.","He does not work here.","We do not have time.","It is not cold today.","You are not late.","The bus does not stop here.","They do not speak Arabic."]'::jsonb,
      '["Use not after be.","Use do not with I, you, we, they.","Use does not with he, she, it."]'::jsonb,
      '["Wrong: She not ready. | Correct: She is not ready.","Wrong: He do not work. | Correct: He does not work.","Wrong: I am not like tea. | Correct: I do not like tea."]'::jsonb,
      '["Do not = don''t; does not = doesn''t.","After doesn''t, use the base verb.","Be negatives do not need do or does."]'::jsonb,
      '["Make negative: She is ready.","Complete: He ___ not work here.","Correct: I am not like coffee."]'::jsonb,
      'She is not ready.',
      'She not ready.',
      'He do not work here.',
      'I am not like tea.',
      'He ___ not work here.',
      'does',
      'Does not is followed by the base verb.',
      'True',
      'Correct the sentence: I am not like coffee.',
      'I do not like coffee'
    ),
    (
      'beginner',
      'articles',
      'Articles: a, an, the',
      'articles-core',
      'easy',
      22,
      'Learn when to use a, an, the, and no article.',
      'Articles come before nouns. Use a or an with one non-specific singular countable noun. Use the when the noun is specific, already known, or unique in the context. Use an before a vowel sound.',
      'a/an + singular countable noun; the + specific noun; no article + plural/general/uncountable nouns',
      'Use articles to show whether a noun is new, general, or specific.',
      'Do not use a/an with plural nouns or uncountable nouns.',
      '["I saw a bird.","The bird was near the window.","She is an engineer.","He bought a new phone.","The phone is expensive.","I need water.","Books are useful.","The sun is bright.","Can you open the door?","She has an honest friend."]'::jsonb,
      '["Use an before vowel sounds, not only vowel letters.","Use the when both speaker and listener know the noun.","Do not use a/an before plural nouns."]'::jsonb,
      '["Wrong: She is a engineer. | Correct: She is an engineer.","Wrong: I like the music in general. | Correct: I like music in general.","Wrong: I need a water. | Correct: I need water."]'::jsonb,
      '["An hour uses an because hour starts with a vowel sound.","The can be used with unique things: the moon.","No article is common for general plural nouns."]'::jsonb,
      '["Complete: She is ___ engineer.","Choose: I like ___ books. (books / the books)","Correct: I need a advice."]'::jsonb,
      'She is an engineer.',
      'She is a engineer.',
      'I need a water.',
      'I like the music in general.',
      'She is ___ honest person.',
      'an',
      'Use an before a vowel sound.',
      'True',
      'Correct the sentence: I need a advice.',
      'I need advice'
    ),
    (
      'elementary',
      'prepositions-in-on-at',
      'Prepositions: in / on / at',
      'prepositions-in-on-at-core',
      'medium',
      24,
      'Use in, on, and at for time and place with more confidence.',
      'In, on, and at are common prepositions. For time, use in with months, years, and long periods; on with days and dates; at with exact times. For place, use in for inside areas, on for surfaces, and at for points or specific locations.',
      'Time: in + month/year/period; on + day/date; at + time. Place: in + area/container; on + surface; at + point/location.',
      'Use these prepositions to describe where something is or when something happens.',
      'Do not translate directly from your first language; English prepositions often follow fixed patterns.',
      '["I was born in July.","She studies in the morning.","The meeting is on Monday.","My birthday is on May 5th.","Class starts at nine.","He is at the door.","The keys are on the table.","They live in Erbil.","We met at the station.","There is a picture on the wall."]'::jsonb,
      '["Use at for exact times.","Use on for days and dates.","Use in for months, years, cities, countries, and enclosed spaces."]'::jsonb,
      '["Wrong: I wake up in 7 o''clock. | Correct: I wake up at 7 o''clock.","Wrong: The meeting is in Monday. | Correct: The meeting is on Monday.","Wrong: She lives at Iraq. | Correct: She lives in Iraq."]'::jsonb,
      '["Some expressions are fixed: at night, in the morning, on the weekend in American English.","Use at home, at work, at school for general locations.","Use on for surfaces."]'::jsonb,
      '["Complete: The class starts ___ 8:00.","Choose: The book is ___ the table.","Correct: We met in Monday."]'::jsonb,
      'The class starts at eight.',
      'The class starts in eight.',
      'We met in Monday.',
      'She lives at Iraq.',
      'The book is ___ the table.',
      'on',
      'Use on for days and dates.',
      'True',
      'Correct the sentence: The meeting is in Monday.',
      'The meeting is on Monday'
    ),
    (
      'elementary',
      'adverbs-of-manner',
      'Adjectives and Adverbs',
      'adjectives-and-adverbs-core',
      'medium',
      22,
      'Learn how adjectives describe nouns and adverbs describe verbs, adjectives, or whole actions.',
      'Adjectives describe nouns: a careful driver. Adverbs often describe verbs: drive carefully. Many adverbs end in -ly, but not all. Some words, like fast and hard, can be adjectives or adverbs.',
      'Adjective + noun; verb + adverb; be + adjective',
      'Use adjectives to describe people, things, and places. Use adverbs to describe how, when, where, or how often an action happens.',
      'Do not use an adjective when you need to describe an action.',
      '["She is careful.","She drives carefully.","This is a quick lesson.","He answered quickly.","The food smells good.","They worked hard.","He is a fast runner.","He runs fast.","The room is quiet.","Please speak quietly."]'::jsonb,
      '["Use an adjective after be.","Use an adverb to describe most actions.","Good is an adjective; well is usually an adverb."]'::jsonb,
      '["Wrong: She drives careful. | Correct: She drives carefully.","Wrong: He speaks English good. | Correct: He speaks English well.","Wrong: This is quickly work. | Correct: This is quick work."]'::jsonb,
      '["Not every adverb ends in -ly.","Some linking verbs take adjectives: feel good, look tired.","Hardly does not mean hard."]'::jsonb,
      '["Complete: She speaks ___.","Choose: a ___ answer (quick / quickly)","Correct: He drives dangerous."]'::jsonb,
      'She drives carefully.',
      'She drives careful.',
      'He speaks English good.',
      'This is quickly work.',
      'She speaks English ___.',
      'well',
      'Adjectives describe nouns, and adverbs often describe verbs.',
      'True',
      'Correct the sentence: He drives dangerous.',
      'He drives dangerously'
    ),
    (
      'beginner',
      'countable-and-uncountable-nouns',
      'Countable and Uncountable Nouns',
      'countable-uncountable-core',
      'easy',
      22,
      'Learn which nouns can be counted and how that changes articles and quantifiers.',
      'Countable nouns have singular and plural forms: one book, two books. Uncountable nouns usually do not have a plural form in everyday use: water, advice, information. Use a/an only with singular countable nouns.',
      'Countable: a/an + singular noun, number + plural noun. Uncountable: some + noun, much + noun, a piece of + noun.',
      'Use countable patterns for separate items and uncountable patterns for materials, abstract ideas, and mass nouns.',
      'Do not add -s to common uncountable nouns like advice, information, furniture, homework, and luggage.',
      '["I have a book.","She has three books.","We need some water.","He gave me good advice.","There is a lot of information online.","Can I have a piece of cake?","There are two chairs.","I have much homework.","This furniture is expensive.","We bought some bread."]'::jsonb,
      '["Do not say advices or informations.","Use many with countable plurals.","Use much with uncountable nouns, often in questions and negatives."]'::jsonb,
      '["Wrong: I need an advice. | Correct: I need advice.","Wrong: There are many information. | Correct: There is a lot of information.","Wrong: I bought three bread. | Correct: I bought three loaves of bread."]'::jsonb,
      '["Some nouns can be countable or uncountable with different meanings: chicken, paper, glass.","A lot of works with both countable and uncountable nouns.","Use pieces, bottles, cups, slices, and loaves to count uncountable things."]'::jsonb,
      '["Complete: I need ___ advice.","Choose: many/much homework","Correct: These informations are useful."]'::jsonb,
      'I need some advice.',
      'I need an advice.',
      'There are many information.',
      'These informations are useful.',
      'I have ___ homework.',
      'much',
      'Advice is usually uncountable in English.',
      'True',
      'Correct the sentence: These informations are useful.',
      'This information is useful'
    ),
    (
      'beginner',
      'present-continuous',
      'Present Continuous Tense',
      'present-continuous-core',
      'easy',
      22,
      'Use the present continuous for actions happening now and temporary situations.',
      'The present continuous uses am, is, or are plus verb-ing. It describes actions happening now, around now, temporary situations, and sometimes future arrangements.',
      'Subject + am/is/are + verb-ing',
      'Use it for actions in progress, temporary changes, current projects, and arranged future plans.',
      'Do not normally use it for permanent habits or stative verbs like know, believe, and love in basic English.',
      '["I am studying now.","She is cooking dinner.","They are playing outside.","We are learning grammar this week.","He is working from home today.","It is raining.","Are you listening?","I am not watching TV.","She is meeting her friend tonight.","Prices are rising."]'::jsonb,
      '["Use be before verb-ing.","Do not forget -ing.","Use present simple for routines, not present continuous."]'::jsonb,
      '["Wrong: She cooking now. | Correct: She is cooking now.","Wrong: They are play football. | Correct: They are playing football.","Wrong: I am go to school every day. | Correct: I go to school every day."]'::jsonb,
      '["Now, at the moment, and today often signal present continuous.","Spelling changes: make -> making, run -> running.","Some verbs are usually stative in basic use."]'::jsonb,
      '["Complete: She ___ cooking now.","Make negative: They are playing.","Correct: He working today."]'::jsonb,
      'She is cooking now.',
      'She cooking now.',
      'They are play football.',
      'He working today.',
      'They are ___ outside.',
      'playing',
      'Present continuous needs am, is, or are before verb-ing.',
      'True',
      'Correct the sentence: He working today.',
      'He is working today'
    ),
    (
      'elementary',
      'present-perfect-simple',
      'Present Perfect Simple',
      'present-perfect-simple-core',
      'medium',
      26,
      'Use the present perfect to connect a past action to the present.',
      'The present perfect uses have or has plus the past participle. It often talks about experiences, results, unfinished time, and actions that started in the past and continue now.',
      'Subject + have/has + past participle',
      'Use it for life experiences, recent results, unfinished time periods, and actions continuing until now.',
      'Do not use it with a finished past time like yesterday or last year. Use past simple for finished time.',
      '["I have visited Istanbul.","She has finished her homework.","They have lived here for five years.","We have already eaten.","He has just arrived.","Have you ever tried sushi?","I have not seen that film.","She has lost her keys.","We have studied three lessons today.","The train has left."]'::jsonb,
      '["Use has with he, she, it.","Use the past participle, not the past simple for irregular verbs.","Use past simple with finished time expressions."]'::jsonb,
      '["Wrong: I have saw that film. | Correct: I have seen that film.","Wrong: She have finished. | Correct: She has finished.","Wrong: I have visited London yesterday. | Correct: I visited London yesterday."]'::jsonb,
      '["For and since are common with present perfect.","Ever and never often appear with experiences.","Already, just, and yet are common signal words."]'::jsonb,
      '["Complete: She ___ finished her homework.","Choose: I have seen/saw that film.","Correct: I have visited him yesterday."]'::jsonb,
      'She has finished her homework.',
      'She have finished her homework.',
      'I have saw that film.',
      'I have visited London yesterday.',
      'I have ___ that film.',
      'seen',
      'Use past simple with a finished time like yesterday.',
      'True',
      'Correct the sentence: I have visited him yesterday.',
      'I visited him yesterday'
    ),
    (
      'pre-intermediate',
      'first-conditional',
      'Conditionals: zero, first, and second',
      'conditionals-core',
      'medium',
      28,
      'Learn the basic conditional patterns for facts, real future results, and imagined situations.',
      'Conditionals connect a condition with a result. Zero conditional describes general facts. First conditional describes real future possibilities. Second conditional describes imagined or unlikely present/future situations.',
      'Zero: if + present, present. First: if + present, will + base verb. Second: if + past, would + base verb.',
      'Use conditionals to talk about results, possibilities, advice, plans, and imagination.',
      'Do not use will in the if-clause of a basic first conditional.',
      '["If you heat water, it boils.","If it rains, I will stay home.","If I see Ali, I will tell him.","If she studies, she will pass.","If I had more time, I would travel.","If I were you, I would apologize.","If you press this button, the machine starts.","We will be late if we leave now.","If he knew the answer, he would help us.","If you need me, call me."]'::jsonb,
      '["Use present simple after if in the first conditional.","Use would in the result of the second conditional.","Use zero conditional for facts and rules."]'::jsonb,
      '["Wrong: If it will rain, I will stay home. | Correct: If it rains, I will stay home.","Wrong: If I am you, I would wait. | Correct: If I were you, I would wait.","Wrong: If you heat water, it will boils. | Correct: If you heat water, it boils."]'::jsonb,
      '["The if-clause can come first or second.","Use a comma when the if-clause comes first.","Were is common with I in formal second conditionals."]'::jsonb,
      '["Complete: If it ___, I will stay home.","Choose: If I were you, I would/will wait.","Correct: If it will rain, we will cancel."]'::jsonb,
      'If it rains, I will stay home.',
      'If it will rain, I will stay home.',
      'If I am you, I would wait.',
      'If you heat water, it will boils.',
      'If it ___ tomorrow, we will cancel.',
      'rains',
      'In the first conditional, the if-clause usually uses present simple.',
      'True',
      'Correct the sentence: If it will rain, we will cancel.',
      'If it rains, we will cancel'
    ),
    (
      'beginner',
      'basic-conversation-practice',
      'Basic Conversation Grammar',
      'basic-conversation-grammar-core',
      'easy',
      20,
      'Use simple grammar patterns for greetings, introductions, requests, and everyday answers.',
      'Conversation grammar is grammar used in real speaking. Short answers, polite questions, contractions, and simple follow-up questions help conversations sound natural.',
      'Greeting + be question; question word + auxiliary + subject + verb; short answer + extra detail',
      'Use conversation grammar when meeting people, asking for help, checking information, and keeping a simple conversation going.',
      'Do not answer every question with one word when a short natural phrase is better.',
      '["Hi, I''m Sara.","Nice to meet you.","Where are you from?","I''m from Iraq.","Do you speak English?","Yes, a little.","Can you help me, please?","What do you do?","I''m a student.","See you later."]'::jsonb,
      '["Use polite forms with please and can/could.","Short answers are natural but need the correct auxiliary.","Use contractions in friendly conversation."]'::jsonb,
      '["Wrong: Where you are from? | Correct: Where are you from?","Wrong: Yes, I speak. | Correct: Yes, I do.","Wrong: I am agree. | Correct: I agree."]'::jsonb,
      '["Conversation grammar is often shorter than writing grammar.","Use follow-up questions to continue speaking.","Polite grammar makes requests sound better."]'::jsonb,
      '["Complete: Where ___ you from?","Choose: Yes, I do / Yes, I am for Do you speak English?","Correct: Where you are from?"]'::jsonb,
      'Where are you from?',
      'Where you are from?',
      'Yes, I speak.',
      'I am agree.',
      'Where ___ you from?',
      'are',
      'Short answers should match the auxiliary in the question.',
      'True',
      'Correct the sentence: Where you are from?',
      'Where are you from'
    )
)
insert into public.lessons (
  topic_id,
  title,
  slug,
  difficulty,
  summary,
  explanation,
  formula,
  usage_when,
  usage_when_not,
  examples,
  common_mistakes,
  wrong_correct_examples,
  short_notes,
  mini_practice,
  lesson_order,
  estimated_minutes,
  is_published
)
select
  topics.id,
  lesson_seed.lesson_title,
  lesson_seed.lesson_slug,
  lesson_seed.difficulty,
  lesson_seed.summary,
  lesson_seed.explanation,
  lesson_seed.formula,
  lesson_seed.usage_when,
  lesson_seed.usage_when_not,
  lesson_seed.examples,
  lesson_seed.common_mistakes,
  lesson_seed.wrong_correct_examples,
  lesson_seed.short_notes,
  lesson_seed.mini_practice,
  1,
  lesson_seed.estimated_minutes,
  true
from lesson_seed
join public.grammar_levels levels on levels.slug = lesson_seed.level_slug
join public.grammar_topics topics on topics.level_id = levels.id and topics.slug = lesson_seed.topic_slug
on conflict (topic_id, slug) do update set
  title = excluded.title,
  difficulty = excluded.difficulty,
  summary = excluded.summary,
  explanation = excluded.explanation,
  formula = excluded.formula,
  usage_when = excluded.usage_when,
  usage_when_not = excluded.usage_when_not,
  examples = excluded.examples,
  common_mistakes = excluded.common_mistakes,
  wrong_correct_examples = excluded.wrong_correct_examples,
  short_notes = excluded.short_notes,
  mini_practice = excluded.mini_practice,
  lesson_order = excluded.lesson_order,
  estimated_minutes = excluded.estimated_minutes,
  is_published = true;

with lesson_context as (
  select
    lessons.id as lesson_id,
    topics.id as topic_id,
    lessons.slug as lesson_slug,
    lessons.title,
    lessons.formula,
    lessons.summary,
    lessons.examples ->> 0 as example_one,
    lessons.wrong_correct_examples ->> 0 as wrong_correct_one,
    lessons.common_mistakes ->> 0 as mistake_note,
    core.correct_sentence,
    core.wrong_sentence,
    core.wrong_sentence_two,
    core.wrong_sentence_three,
    core.blank_prompt,
    core.blank_answer,
    core.tf_prompt,
    core.tf_answer,
    core.correction_prompt,
    core.correction_answer
  from public.lessons lessons
  join public.grammar_topics topics on topics.id = lessons.topic_id
  join (
    values
      ('verb-to-be-am-is-are-core','She is happy.','She are happy.','I is a student.','Are he ready?','He ___ my brother.','is','The sentence "They are at school" is correct.','True','Correct the sentence: I is tired.','I am tired'),
      ('subject-pronouns-core','She is my sister.','Her is my sister.','Me am ready.','Them are students.','Ali and Dana are here. ___ are ready.','They','The pronoun "I" is always written with a capital letter.','True','Correct the sentence: Me am ready.','I am ready'),
      ('present-simple-core','She works every day.','She work every day.','Does he plays football?','I am go to school.','He ___ coffee every morning.','drinks','After does, the main verb stays in the base form.','True','Correct the sentence: She do not play football.','She does not play football'),
      ('past-simple-core','She visited Paris last year.','She visit Paris last year.','Did you went home?','I didn''t watched TV.','I ___ my friend yesterday.','visited','After did, use the base verb.','True','Correct the sentence: He didn''t went home.','He did not go home'),
      ('future-will-going-to-core','I will call you later.','I will to call you later.','She going to study tonight.','I am going to will travel.','She ___ going to visit us.','is','Going to needs a form of be before it.','True','Correct the sentence: I will to help you.','I will help you'),
      ('basic-questions-core','Are you ready?','You are ready?','Does she works here?','Do he like coffee?','___ do you live?','Where','With be, the question starts with am, is, or are.','True','Correct the sentence: Does he works here?','Does he work here'),
      ('basic-negatives-core','She is not ready.','She not ready.','He do not work here.','I am not like tea.','He ___ not work here.','does','Does not is followed by the base verb.','True','Correct the sentence: I am not like coffee.','I do not like coffee'),
      ('articles-core','She is an engineer.','She is a engineer.','I need a water.','I like the music in general.','She is ___ honest person.','an','Use an before a vowel sound.','True','Correct the sentence: I need a advice.','I need advice'),
      ('prepositions-in-on-at-core','The class starts at eight.','The class starts in eight.','We met in Monday.','She lives at Iraq.','The book is ___ the table.','on','Use on for days and dates.','True','Correct the sentence: The meeting is in Monday.','The meeting is on Monday'),
      ('adjectives-and-adverbs-core','She drives carefully.','She drives careful.','He speaks English good.','This is quickly work.','She speaks English ___.','well','Adjectives describe nouns, and adverbs often describe verbs.','True','Correct the sentence: He drives dangerous.','He drives dangerously'),
      ('countable-uncountable-core','I need some advice.','I need an advice.','There are many information.','These informations are useful.','I have ___ homework.','much','Advice is usually uncountable in English.','True','Correct the sentence: These informations are useful.','This information is useful'),
      ('present-continuous-core','She is cooking now.','She cooking now.','They are play football.','He working today.','They are ___ outside.','playing','Present continuous needs am, is, or are before verb-ing.','True','Correct the sentence: He working today.','He is working today'),
      ('present-perfect-simple-core','She has finished her homework.','She have finished her homework.','I have saw that film.','I have visited London yesterday.','I have ___ that film.','seen','Use past simple with a finished time like yesterday.','True','Correct the sentence: I have visited him yesterday.','I visited him yesterday'),
      ('conditionals-core','If it rains, I will stay home.','If it will rain, I will stay home.','If I am you, I would wait.','If you heat water, it will boils.','If it ___ tomorrow, we will cancel.','rains','In the first conditional, the if-clause usually uses present simple.','True','Correct the sentence: If it will rain, we will cancel.','If it rains, we will cancel'),
      ('basic-conversation-grammar-core','Where are you from?','Where you are from?','Yes, I speak.','I am agree.','Where ___ you from?','are','Short answers should match the auxiliary in the question.','True','Correct the sentence: Where you are from?','Where are you from')
  ) as core(lesson_slug, correct_sentence, wrong_sentence, wrong_sentence_two, wrong_sentence_three, blank_prompt, blank_answer, tf_prompt, tf_answer, correction_prompt, correction_answer)
    on core.lesson_slug = lessons.slug
),
generated_questions as (
  select
    lesson_id,
    topic_id,
    question_order,
    question_scope,
    difficulty,
    question_type,
    prompt,
    options,
    correct_answer,
    explanation,
    wrong_answer_explanation
  from lesson_context
  cross join lateral (
    values
      (1, 'practice', 'easy', 'multiple_choice', 'Choose the correct sentence for ' || title || '.', jsonb_build_array(wrong_sentence, correct_sentence, wrong_sentence_two, wrong_sentence_three), correct_sentence, 'This sentence follows the lesson rule.', 'Review the structure and compare the subject, auxiliary, or word form.'),
      (2, 'practice', 'easy', 'fill_blank', blank_prompt, '[]'::jsonb, blank_answer, 'The blank needs the grammar form taught in this lesson.', 'Look at the subject and the time/meaning of the sentence.'),
      (3, 'practice', 'easy', 'true_false', tf_prompt, jsonb_build_array('True', 'False'), tf_answer, 'This statement checks the main rule from the lesson.', 'Return to the formula and examples before trying again.'),
      (4, 'practice', 'medium', 'sentence_correction', correction_prompt, '[]'::jsonb, correction_answer, 'The corrected sentence uses the target structure accurately.', 'Find the wrong verb, pronoun, article, preposition, or word order.'),
      (5, 'practice', 'medium', 'multiple_choice', 'Which sentence should you use in real conversation?', jsonb_build_array(correct_sentence, wrong_sentence, wrong_sentence_two, wrong_sentence_three), correct_sentence, 'Natural grammar follows the same pattern as the lesson examples.', 'The incorrect answers contain common beginner mistakes.'),
      (6, 'practice', 'medium', 'fill_blank', 'Complete the grammar pattern: ' || coalesce(formula, summary), '[]'::jsonb, blank_answer, 'The answer completes the pattern in this lesson.', 'Focus on the missing grammar word, not only vocabulary.'),
      (7, 'practice', 'review', 'true_false', 'This is a common mistake: ' || wrong_sentence, jsonb_build_array('True', 'False'), 'True', 'The sentence shown is intentionally wrong and should be corrected.', 'Mistake-focused questions help you notice errors faster.'),
      (8, 'practice', 'review', 'sentence_correction', 'Fix this mistake: ' || wrong_sentence, '[]'::jsonb, correct_sentence, 'The corrected sentence removes the common mistake.', 'Compare your answer with the correct version word by word.'),
      (9, 'lesson_test', 'easy', 'multiple_choice', 'Lesson test: choose the accurate sentence.', jsonb_build_array(wrong_sentence_three, wrong_sentence_two, correct_sentence, wrong_sentence), correct_sentence, 'This checks whether you can recognize the correct form.', 'Eliminate answers with wrong word order or wrong verb form.'),
      (10, 'lesson_test', 'medium', 'fill_blank', 'Lesson test: ' || blank_prompt, '[]'::jsonb, blank_answer, 'The correct answer matches the lesson structure.', 'Use the formula before choosing the answer.'),
      (11, 'lesson_test', 'medium', 'sentence_correction', 'Lesson test: ' || correction_prompt, '[]'::jsonb, correction_answer, 'This tests correction skill, not only recognition.', 'Identify the exact grammar mistake first.'),
      (12, 'lesson_test', 'hard', 'multiple_choice', 'Which sentence is NOT correct?', jsonb_build_array(correct_sentence, example_one, wrong_sentence, correction_answer), wrong_sentence, 'The wrong sentence breaks the target grammar rule.', 'This is an error detection test.'),
      (13, 'mistake_focus', 'review', 'sentence_correction', 'Mistake review: ' || wrong_sentence_two, '[]'::jsonb, correct_sentence, 'This review question reinforces the correct grammar pattern.', 'If your answer is wrong, save it and review the lesson examples.')
  ) as q(question_order, question_scope, difficulty, question_type, prompt, options, correct_answer, explanation, wrong_answer_explanation)
)
insert into public.questions (
  lesson_id,
  topic_id,
  question_type,
  difficulty,
  question_scope,
  prompt,
  options,
  correct_answer,
  explanation,
  wrong_answer_explanation,
  question_order,
  is_published
)
select
  lesson_id,
  topic_id,
  question_type::public.question_type,
  difficulty,
  question_scope,
  prompt,
  options,
  correct_answer,
  explanation,
  wrong_answer_explanation,
  question_order,
  true
from generated_questions
where not exists (
  select 1
  from public.questions existing
  where existing.lesson_id = generated_questions.lesson_id
    and existing.question_order = generated_questions.question_order
    and existing.question_scope = generated_questions.question_scope
);
